### ISSUE TITLE
How do I use it as an external resource?

### ISSUE THREAD

**Issue by chudur-budur** [jamesplease/latex-to-unicode.js#6]
Is there any way I could use it through [JSdelivr](https://www.jsdelivr.com/package/npm/latex-to-unicode)? 

Like this?

```lang-js
<script src="https://cdn.jsdelivr.net/npm/latex-to-unicode@0.1.0/index.min.js"></script>
```

**Comment by jamesplease** [comment]
This package is Node only; browser environments aren't supported. So you won't be able to use it using a method like what you suggested.

You could add your own build step to resolve the `require` statements and output a single JS file to load in the browser, though.
